In [2]:
import pandas as pd
from pandas import ExcelWriter
from pandas import ExcelFile

df = pd.read_excel('SwimCoach.xlsx')

df

,College Name,Head Coach Name,Head Coach Email
0,Ohio State University,Bill Dorenkott,dorenkott.2@osu.edu
1,Michigan University,Mike Bottom,mbottom@umich.edu
2,University of Indiana,Ray Looze,rlooze@indiana.edu
3,Northwestern University,Katie Robinson,katie.robinson@northwestern.edu
4,University of Minnesota,Kelly Kremer,kreme010@umn.edu
...,...,...,...
67,Virginia Tech University,Segio Lopez Miro,sergio@vt.edu
68,Wake Forrest University,NaN,NaN
69,University of Pittsburgh,John Hargis,jhargis@athletics.pitt.edu
70,Syracuse University,Lou Walker,lrwalker@syr.edu
71,University of Louisville,Arthur Albiero,arthur@GoCards.com

In [3]:
!pip install ipython-sql

Collecting ipython-sql
  Downloading ipython_sql-0.4.0-py3-none-any.whl (19 kB)
Collecting prettytable<1
  Downloading prettytable-0.7.2.tar.bz2 (21 kB)
Requirement already satisfied: sqlalchemy>=0.6.7 in ./opt/anaconda3/lib/python3.8/site-packages (from ipython-sql) (1.3.20)
Collecting sqlparse
  Downloading sqlparse-0.4.1-py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 1.5 MB/s  eta 0:00:01
Requirement already satisfied: six in ./opt/anaconda3/lib/python3.8/site-packages (from ipython-sql) (1.15.0)
Requirement already satisfied: ipython-genutils>=0.1.0 in ./opt/anaconda3/lib/python3.8/site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: ipython>=1.0 in ./opt/anaconda3/lib/python3.8/site-packages (from ipython-sql) (7.19.0)
Requirement already satisfied: traitlets>=4.2 in ./opt/anaconda3/lib/python3.8/site-packages (from ipython>=1.0->ipython-sql) (5.0.5)
Requirement already satisfied: jedi>=0.10 in ./opt/anaconda3/lib/python3.8/site-packages (from ipython>=1.0->ipython-sql) (0.17.1)
Requirement already satisfied: pygments in ./opt/anaconda3/lib/python3.8/site-packages (from ipython>=1.0->ipython-sql) (2.7.2)
Requirement already satisfied: pickleshare in ./opt/anaconda3/lib/python3.8/site-packages (from ipython>=1.0->ipython-sql) (0.7.5)
Requirement already satisfied: appnope; sys_platform == "darwin" in ./opt/anaconda3/lib/python3.8/site-packages (from ipython>=1.0->ipython-sql) (0.1.0)
Requirement already satisfied: backcall in ./opt/anaconda3/lib/python3.8/site-packages (from ipython>=1.0->ipython-sql) (0.2.0)
Requirement already satisfied: decorator in ./opt/anaconda3/lib/python3.8/site-packages (from ipython>=1.0->ipython-sql) (4.4.2)
Requirement already satisfied: setuptools>=18.5 in ./opt/anaconda3/lib/python3.8/site-packages (from ipython>=1.0->ipython-sql) (50.3.1.post20201107)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in ./opt/anaconda3/lib/python3.8/site-packages (from ipython>=1.0->ipython-sql) (3.0.8)
Requirement already satisfied: pexpect>4.3; sys_platform != "win32" in ./opt/anaconda3/lib/python3.8/site-packages (from ipython>=1.0->ipython-sql) (4.8.0)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in ./opt/anaconda3/lib/python3.8/site-packages (from jedi>=0.10->ipython>=1.0->ipython-sql) (0.7.0)
Requirement already satisfied: wcwidth in ./opt/anaconda3/lib/python3.8/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=1.0->ipython-sql) (0.2.5)
Requirement already satisfied: ptyprocess>=0.5 in ./opt/anaconda3/lib/python3.8/site-packages (from pexpect>4.3; sys_platform != "win32"->ipython>=1.0->ipython-sql) (0.6.0)
Building wheels for collected packages: prettytable
  Building wheel for prettytable (setup.py) ... done
  Created wheel for prettytable: filename=prettytable-0.7.2-py3-none-any.whl size=13700 sha256=1d3748d1cb48403135cf135aee7a36ef08868302fb07b78b452e5af14b8a41b0
  Stored in directory: /Users/aayushdeshpande/Library/Caches/pip/wheels/46/60/6c/bb25d05df22906786206e901e9354bb3061061191116768bee
Successfully built prettytable
Installing collected packages: prettytable, sqlparse, ipython-sql
Successfully installed ipython-sql-0.4.0 prettytable-0.7.2 sqlparse-0.4.1

In [10]:
import sqlite3

In [11]:
dbname = 'SwimDataDb'
conn = sqlite3.connect(dbname + '.sqlite')

In [19]:
Sw = conn.cursor()
Sw.execute('SELECT * FROM SwimCoach')
for row in Sw:
    print(row)

(0, 'Ohio State University', 'Bill Dorenkott', 'dorenkott.2@osu.edu')
(1, 'Michigan University', 'Mike Bottom', 'mbottom@umich.edu')
(2, 'University of Indiana', 'Ray Looze', 'rlooze@indiana.edu')
(3, 'Northwestern University', 'Katie Robinson', 'katie.robinson@northwestern.edu')
(4, 'University of Minnesota', 'Kelly Kremer', 'kreme010@umn.edu')
(5, 'University of Wisconsin', 'Yuri Suguiyama', 'YFS@athletics.wisc.edu')
(6, 'Purdue University', 'Dan Ross', 'dross@purdue.edu')
(7, 'Penn State University', 'Tim Murphy', 'tdm15@psu.edu')
(8, 'University of Illinois', 'Sue Novitsky', 'novitsky@illinois.edu')
(9, 'Michigan State University', 'Matt Gianiodis', 'gianiodi@ath.msu.edu')
(10, 'University of Iowa', 'Marc Long', 'marc-long@uiowa.edu')
(11, 'University of Nebraska', 'Pablo Morales', 'pmorales@huskers.com')
(12, 'Rutgers University', 'Jon Maccoll', 'jmaccoll@scarletknights.com')
(13, 'Maryland University', None, None)
(14, 'Harvard University', 'Kevin Tyyrell', 'pitter@fas.harvard.edu')
(15, 'Princeton University', 'Matt Crispino', 'crispino@princeton.edu')
(16, 'Yale University', 'Jim Henry', 'james.henry@yale.edu')
(17, 'Columbia University', 'Scott Donie', 'srd2158@columbia.edu')
(18, 'Brown University', 'Kevin Norman', 'kevin_norman@brown.edu')
(19, 'Cornell University', 'Wes Newman', 'wjn3@cornell.edu')
(20, 'Darthmouth College', 'James Holder', 'James.F.Holder@dartmouth.edu')
(21, 'University of Pennslyvania', 'Steve Donahue', 'parkss@upenn.edu')
(22, 'University of Alabama', 'Coley Stickels', 'ctstickels@ia.ua.edu')
(23, 'University of Arkansas', 'Neil Harper', 'nharper1@uark.edu')
(24, 'University of Auburn', 'Gary Taylor', 'getaylor@auburn.edu')
(25, 'University of Florida', 'Anthony Nesty', 'anthonyn@gators.ufl.edu')
(26, 'University of Georgia', 'Jack Baurle', 'jbauerle@sports.uga.edu\n')
(27, 'University of Kentucky', 'Lars Jordgensen', 'lars.jorgensen@uky.edu')
(28, 'Lousiana State University', 'Dave Geyer', 'dgeyer@lsu.edu')
(29, 'Ole Mississippi University', None, None)
(30, 'Mississippi State University', None, None)
(31, 'University of South Carolina', 'McGee Moody', 'pmmoody@mailbox.sc.edu')
(32, 'University of Tenneesee', 'Matt Kredich', 'mkredich@utk.edu')
(33, 'Vanderbilt University', 'Jeremy Organ', 'jeremy.s.organ@vanderbilt.edu')
(34, 'Texas A&M University', 'Jay Holmes', 'sbultman@athletics.tamu.edu')
(35, 'University of Missouri', 'Andrew Grevers', 'greversa@missouri.edu')
(36, 'Amherst', 'Nick Nichols', 'nnichols@amherst.edu')
(37, 'Bates', 'Peter Casares', 'pcasacares@bates.edu')
(38, 'Bowdoin', 'Brad Burnhan', 'bburnham@bowdoin.edu')
(39, 'Colby', 'Tim Burton', 'tkburton@colby.edu')
(40, 'Hamilton', 'John Geissinger', 'jgeissin@hamilton.edu')
(41, 'Middlebury', 'Bob Rueppel', 'rrueppel@middlebury.edu')
(42, 'Trinity', 'Scott Trompeter', 'strompet@trinity.edu')
(43, 'Tufts', 'Adam Hoyt', 'adam.hoyt@tufts.edu')
(44, 'Wesleyan', 'Peter Soloman', 'psolomon@wesleyan.edu')
(45, 'Williams', 'Steve Kuster', 'skuster@williams.edu')
(46, 'University of Arizona', 'Augie Busch', 'abusch@email.arizona.edu')
(47, 'Arizona State University', 'Bob Bowman', 'bob.bowman@asu.edu')
(48, 'University of California', 'David Durden', 'durden@berkeley.edu')
(49, 'University of Oregon', None, None)
(50, 'Oregon State University', 'Jennifer Buffin', 'Jennifer.Buffin@oregonstate.edu')
(51, 'Stanford University', 'Dan Schemmel', 'schemmel@stanford.edu')
(52, 'UCLA', 'Jordan Wolfrum', 'jwolfrum@athletics.ucla.edu')
(53, 'USC', 'Jeremy Kipp', 'jkipp@usc.edu')
(54, 'U. Washington', 'Craig Nisgor', 'swim@ussportscamps.com.')
(55, 'Washington State University', 'Matt Leach', 'matt.leach@wsu.edu')
(56, 'University of Colorado', 'Anne Shawhan', None)
(57, 'University of Utah', 'Joe Dykstra', 'jdykstra@huntsman.utah.edu')
(58, 'Boston College', 'Michael Stephens', 'stephemd@bc.edu')
(59, 'Clemson University', None, None)
(60, 'Duke University', 'Dan Colella', 'dan.colella@duke.edu')
(61, 'Florida State University', 'Neal Studd', 'dcarrington@fsu.edu')
(62, 'Georgia Tech University', 'Bill Koppelman', None)
(63, 'University of Miami', 'Zach Hinsley', 'hinslez@miamioh.edu')
(64, 'University of North Carolina', 'Mark Gangloff', 'mgangloff@unc.edu')
(65, 'North Carolina State University', 'Braden Holloway', 'bchollo2@ncsu.edu')
(66, 'University of Virginia', 'Todd DeSorbo', 'tmd2z@virginia.edu')
(67, 'Virginia Tech University', 'Segio Lopez Miro', 'sergio@vt.edu')
(68, 'Wake Forrest University', None, None)
(69, 'University of Pittsburgh', 'John Hargis', 'jhargis@athletics.pitt.edu')
(70, 'Syracuse University', 'Lou Walker', 'lrwalker@syr.edu')
(71, 'University of Louisville', 'Arthur Albiero', 'arthur@GoCards.com')

In [ ]:
df.to_sql(name='SwimCoach', con=conn)